#
#   ▄▄▄▄   ▓█████▄▄▄█████▓▄▄▄█████▓▓█████  ██▀███       ██████ ▓█████  ▄████▄   █    ██  ██▀███   ██▓▄▄▄█████▓▓██   ██▓
#  ▓█████▄ ▓█   ▀▓  ██▒ ▓▒▓  ██▒ ▓▒▓█   ▀ ▓██ ▒ ██▒   ▒██    ▒ ▓█   ▀ ▒██▀ ▀█   ██  ▓██▒▓██ ▒ ██▒▓██▒▓  ██▒ ▓▒ ▒██  ██▒
#  ▒██▒ ▄██▒███  ▒ ▓██░ ▒░▒ ▓██░ ▒░▒███   ▓██ ░▄█ ▒   ░ ▓██▄   ▒███   ▒▓█    ▄ ▓██  ▒██░▓██ ░▄█ ▒▒██▒▒ ▓██░ ▒░  ▒██ ██░
#  ▒██░█▀  ▒▓█  ▄░ ▓██▓ ░ ░ ▓██▓ ░ ▒▓█  ▄ ▒██▀▀█▄       ▒   ██▒▒▓█  ▄ ▒▓▓▄ ▄██▒▓▓█  ░██░▒██▀▀█▄  ░██░░ ▓██▓ ░   ░ ▐██▓░
#  ░▓█  ▀█▓░▒████▒ ▒██▒ ░   ▒██▒ ░ ░▒████▒░██▓ ▒██▒   ▒██████▒▒░▒████▒▒ ▓███▀ ░▒▒█████▓ ░██▓ ▒██▒░██░  ▒██▒ ░   ░ ██▒▓░
#  ░▒▓███▀▒░░ ▒░ ░ ▒ ░░     ▒ ░░   ░░ ▒░ ░░ ▒▓ ░▒▓░   ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ░▒ ▒  ░░▒▓▒ ▒ ▒ ░ ▒▓ ░▒▓░░▓    ▒ ░░      ██▒▒▒
#  ▒░▒   ░  ░ ░  ░   ░        ░     ░ ░  ░  ░▒ ░ ▒░   ░ ░▒  ░ ░ ░ ░  ░  ░  ▒   ░░▒░ ░ ░   ░▒ ░ ▒░ ▒ ░    ░     ▓██ ░▒░
#   ░    ░    ░    ░        ░         ░     ░░   ░    ░  ░  ░     ░   ░         ░░░ ░ ░   ░░   ░  ▒ ░  ░       ▒ ▒ ░░
#   ░         ░  ░                    ░  ░   ░              ░     ░  ░░ ░         ░        ░      ░            ░ ░
#        ░                                                            ░                                        ░ ░
#
#   Version: 1.4 | BungeeCord Version
#   Messages - it_IT [Italiano]
#
#   Wiki: https://zs0bye.gitbook.io/bettersecurity/plugins/bettersecurity
#


#  _________                              __________
#  __  ____/_____________________________ ___  /__(_)
#  _  / __ _  _ \_  __ \  _ \_  ___/  __ `/_  /__  /
#  / /_/ / /  __/  / / /  __/  /   / /_/ /_  / _  /
#  \____/  \___//_/ /_/\___//_/    \__,_/ /_/  /_/
#
is_not_number: '%prefix%&cPer favore, inserisci un numero valido!'
insufficient_permissions: '%prefix%&cNon hai abbastanza permessi!'
update_notification: '%prefix%È disponibile un nuovo aggiornamento! (Attualmente hai: &c%old%&7), Scarica la nuova versione &e%new%&7 da &ahttps://www.spigotmc.org/resources/bettersecurity-%E2%9C%A8-the-best-security-for-your-server.105608/'


#  _________                              _________           _____________    ____________       _____
#  __  ____/____________ _________ _____________  /_____      ______  /__(_)   ___    |__(_)___  ___  /______
#  _  /    _  __ \_  __ `__ \  __ `/_  __ \  __  /_  __ \     _  __  /__  /    __  /| |_  /_  / / /  __/  __ \
#  / /___  / /_/ /  / / / / / /_/ /_  / / / /_/ / / /_/ /     / /_/ / _  /     _  ___ |  / / /_/ // /_ / /_/ /
#  \____/  \____//_/ /_/ /_/\__,_/ /_/ /_/\__,_/  \____/      \__,_/  /_/      /_/  |_/_/  \__,_/ \__/ \____/
#
Help_Command:
  texts:
    - ''
    - '&6 ┃ &e%version% ‑ %proxy%'
    - ''
    - '&6 ┃ &d[] &7⁼ &7Opzionale'
    - '&6 ┃ &c‹› &7⁼ &7Richiesto'
    - ''
    - '&6 ┃ &f/%command% help &7‑ &eApri questa pagina.'
    - '&6 ┃ &f/%command% about &7‑ &eMostra le info del plug-in.'
    - '&6 ┃ &f/%command% reload &7‑ &eRicarica le configurazioni.'
    - ''
    - '&6 ┃ &e%author%'
    - ''


#  _________                              _________           _____________    _____________                    _____
#  __  ____/____________ _________ _____________  /_____      ______  /__(_)   ___  __ \__(_)___________ __________(_)___________ _
#  _  /    _  __ \_  __ `__ \  __ `/_  __ \  __  /_  __ \     _  __  /__  /    __  /_/ /_  /_  ___/  __ `/_  ___/_  /_  ___/  __ `/
#  / /___  / /_/ /  / / / / / /_/ /_  / / / /_/ / / /_/ /     / /_/ / _  /     _  _, _/_  / / /__ / /_/ /_  /   _  / / /__ / /_/ /
#  \____/  \____//_/ /_/ /_/\__,_/ /_/ /_/\__,_/  \____/      \__,_/  /_/      /_/ |_| /_/  \___/ \__,_/ /_/    /_/  \___/ \__,_/
#
Reload_Command:
  configurations: '%prefix%Le configurazioni sono state ricaricate!'


#    ____                                _   _             _  __           _        ____
#   |  _ \ _____      _____ _ __ ___  __| | | |__  _   _  | |/ /   _  ___ | |_ ___ |  _ \ ___  ___  ___  _   _ _ __ ___ ___  ___
#   | |_) / _ \ \ /\ / / _ \ '__/ _ \/ _` | | '_ \| | | | | ' / | | |/ _ \| __/ _ \| |_) / _ \/ __|/ _ \| | | | '__/ __/ _ \/ __|
#   |  __/ (_) \ V  V /  __/ | |  __/ (_| | | |_) | |_| | | . \ |_| | (_) | || (_) |  _ <  __/\__ \ (_) | |_| | | | (_|  __/\__ \
#   |_|   \___/ \_/\_/ \___|_|  \___|\__,_| |_.__/ \__, | |_|\_\__, |\___/ \__\___/|_| \_\___||___/\___/ \__,_|_|  \___\___||___/
#                                                  |___/       |___/