#
#   ▄▄▄▄   ▓█████▄▄▄█████▓▄▄▄█████▓▓█████  ██▀███       ██████ ▓█████  ▄████▄   █    ██  ██▀███   ██▓▄▄▄█████▓▓██   ██▓
#  ▓█████▄ ▓█   ▀▓  ██▒ ▓▒▓  ██▒ ▓▒▓█   ▀ ▓██ ▒ ██▒   ▒██    ▒ ▓█   ▀ ▒██▀ ▀█   ██  ▓██▒▓██ ▒ ██▒▓██▒▓  ██▒ ▓▒ ▒██  ██▒
#  ▒██▒ ▄██▒███  ▒ ▓██░ ▒░▒ ▓██░ ▒░▒███   ▓██ ░▄█ ▒   ░ ▓██▄   ▒███   ▒▓█    ▄ ▓██  ▒██░▓██ ░▄█ ▒▒██▒▒ ▓██░ ▒░  ▒██ ██░
#  ▒██░█▀  ▒▓█  ▄░ ▓██▓ ░ ░ ▓██▓ ░ ▒▓█  ▄ ▒██▀▀█▄       ▒   ██▒▒▓█  ▄ ▒▓▓▄ ▄██▒▓▓█  ░██░▒██▀▀█▄  ░██░░ ▓██▓ ░   ░ ▐██▓░
#  ░▓█  ▀█▓░▒████▒ ▒██▒ ░   ▒██▒ ░ ░▒████▒░██▓ ▒██▒   ▒██████▒▒░▒████▒▒ ▓███▀ ░▒▒█████▓ ░██▓ ▒██▒░██░  ▒██▒ ░   ░ ██▒▓░
#  ░▒▓███▀▒░░ ▒░ ░ ▒ ░░     ▒ ░░   ░░ ▒░ ░░ ▒▓ ░▒▓░   ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ░▒ ▒  ░░▒▓▒ ▒ ▒ ░ ▒▓ ░▒▓░░▓    ▒ ░░      ██▒▒▒
#  ▒░▒   ░  ░ ░  ░   ░        ░     ░ ░  ░  ░▒ ░ ▒░   ░ ░▒  ░ ░ ░ ░  ░  ░  ▒   ░░▒░ ░ ░   ░▒ ░ ▒░ ▒ ░    ░     ▓██ ░▒░
#   ░    ░    ░    ░        ░         ░     ░░   ░    ░  ░  ░     ░   ░         ░░░ ░ ░   ░░   ░  ▒ ░  ░       ▒ ▒ ░░
#   ░         ░  ░                    ░  ░   ░              ░     ░  ░░ ░         ░        ░      ░            ░ ░
#        ░                                                            ░                                        ░ ░
#
#   Version: 1.6 | Bukkit Version
#   Messages - en_US [English]
#
#   Wiki: https://zs0bye.gitbook.io/bettersecurity/plugins/bettersecurity
#


#  _________                              ______
#  __  ____/_____________________________ ___  /
#  _  / __ _  _ \_  __ \  _ \_  ___/  __ `/_  /
#  / /_/ / /  __/  / / /  __/  /   / /_/ /_  /
#  \____/  \___//_/ /_/\___//_/    \__,_/ /_/
#
is_not_number: '%prefix%&cPlease enter a valid number!'
insufficient_permissions: '%prefix%&cYou don''t have enough permissions!'
update_notification: '%prefix%A new update is available! (You currently have: &c%old%&7), Download the new version &e%new%&7 from &ahttps://www.spigotmc.org/resources/bettersecurity-%E2%9C%A8-the-best-security-for-your-server.105608/'


#  ______  __    ______             _________                                         _________
#  ___  / / /_______  /_______      __  ____/____________ __________ _________ _____________  /
#  __  /_/ /_  _ \_  /___  __ \     _  /    _  __ \_  __ `__ \_  __ `__ \  __ `/_  __ \  __  /
#  _  __  / /  __/  / __  /_/ /     / /___  / /_/ /  / / / / /  / / / / / /_/ /_  / / / /_/ /
#  /_/ /_/  \___//_/  _  .___/      \____/  \____//_/ /_/ /_//_/ /_/ /_/\__,_/ /_/ /_/\__,_/
#                     /_/
Help_Command:
  texts:
    1:
      - ''
      - '&6 ┃ &e%version% - %server%'
      - ''
      - '&6 ┃ &d[] &7⁼ &7Optional'
      - '&6 ┃ &c‹› &7⁼ &7Required'
      - ''
      - '&6 ┃ &f/%command% help &7‑ &eOpen this page.'
      - '&6 ┃ &f/%command% about &7‑ &eShow plug-in info.'
      - '&6 ┃ &f/%command% reload &7‑ &eReload configurations.'
      - ''
      - '&6 ┃ &7Page &e%page%&7/&e%maxpage%'
      - '&6 ┃ &e%author%'
      - ''
  placeholders:
    max_page: 'Max'
  errors:
    page_not_found: '%prefix%&cThis page was not found!'


#  ________     ______            _________   _________                                         _________
#  ___  __ \_______  /___________ ______  /   __  ____/____________ __________ _________ _____________  /
#  __  /_/ /  _ \_  /_  __ \  __ `/  __  /    _  /    _  __ \_  __ `__ \_  __ `__ \  __ `/_  __ \  __  /
#  _  _, _//  __/  / / /_/ / /_/ // /_/ /     / /___  / /_/ /  / / / / /  / / / / / /_/ /_  / / / /_/ /
#  /_/ |_| \___//_/  \____/\__,_/ \__,_/      \____/  \____//_/ /_/ /_//_/ /_/ /_/\__,_/ /_/ /_/\__,_/
#
Reload_Command:
  configurations: '%prefix%Configurations have been reloaded!'


#    ____                                _   _             _  __           _        ____
#   |  _ \ _____      _____ _ __ ___  __| | | |__  _   _  | |/ /   _  ___ | |_ ___ |  _ \ ___  ___  ___  _   _ _ __ ___ ___  ___
#   | |_) / _ \ \ /\ / / _ \ '__/ _ \/ _` | | '_ \| | | | | ' / | | |/ _ \| __/ _ \| |_) / _ \/ __|/ _ \| | | | '__/ __/ _ \/ __|
#   |  __/ (_) \ V  V /  __/ | |  __/ (_| | | |_) | |_| | | . \ |_| | (_) | || (_) |  _ <  __/\__ \ (_) | |_| | | | (_|  __/\__ \
#   |_|   \___/ \_/\_/ \___|_|  \___|\__,_| |_.__/ \__, | |_|\_\__, |\___/ \__\___/|_| \_\___||___/\___/ \__,_|_|  \___\___||___/
#                                                  |___/       |___/